INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 1 on Medium', ' ', 15, 15);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 1 on Hard', ' ', 25, 40);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 2 on Medium', ' ', 15, 55);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 2 on Hard', ' ', 25, 80);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 3 on Medium', ' ', 15, 95);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 3 on Hard', ' ', 25, 120);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 4 on Medium', ' ', 15, 135);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 4 on Hard', ' ', 25, 160);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 5 on Medium', ' ', 15, 175);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 5 on Hard', ' ', 25, 200);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 6 on Medium', ' ', 15, 215);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 6 on Hard', ' ', 25, 240);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 7 on Medium', ' ', 15, 255);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 7 on Hard', ' ', 25, 280);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 8 on Medium', ' ', 15, 295);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 8 on Hard', ' ', 25, 320);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 9 on Medium', ' ', 15, 335);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 9 on Hard', ' ', 25, 360);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 10 on Medium', ' ', 15, 375);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete Level 10 on Hard', ' ', 25, 400);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete every level on Hard', ' ', 40, 440);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Use the laser in combination with the EMP Grenade to create a dispersion field', ' ', 20, 460);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Use only alternate fire to beat a level', ' ', 20, 480);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Keep the target reticule locked on to a Flyer for 10 seconds', ' ', 20, 500);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Master the crouch-jump by jumping ten feet', ' ', 20, 520);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Discover the hidden weapons cache (Level 4)', ' ', 20, 540);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Discover the Well of Eons (Level 8)', ' ', 20, 560);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Find all 10 Golden Armor pieces (one each level)', ' ', 20, 580);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Find all 5 missing colonists (one every other level)', ' ', 20, 600);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Climb to the highest spot in the game', ' ', 20, 620);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete a level in co-op with someone that hasn\'t previously completed it', ' ', 20, 640);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Complete a level with a stranger in co-op', ' ', 10, 650);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Play Level 2 from both perspectives in co-op', ' ', 15, 665);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Play Level 6 from both perspectives in co-op', ' ', 15, 680);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Create a custom game type and play it with at least 7 friends', ' ', 20, 700);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Be a part of something big - play online at the same time as 10,000 other players', ' ', 10, 710);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('6 Degrees - a viral achievement that starts with the first 100 hundred players online', ' ', 10, 720);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Place in the top half on a Death Match (ranked)', ' ', 10, 730);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Place #1 in a Death Match (ranked)', ' ', 30, 760);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Contribute your share of the kills in a winning Team Death Match (ranked)', ' ', 10, 770);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Leading contributor of kills in a winning Team Death Match (ranked)', ' ', 30, 800);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Your team captures and successfully defends the flag in a CTF game (ranked)', ' ', 10, 810);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('You capture a flag and kill an enemy flag carrier in a single CTF game (ranked)', ' ', 30, 840);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Your team destroys and successfully defends the objective in an Objective game (ranked)', ' ', 10, 850);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('You destroy the objective and defuse a bomb in a single Objective game (ranked)', ' ', 30, 880);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Win a game on every map (ranked) and acquire all other multiplayer achievements', ' ', 40, 920);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Reserved for DLC: a new single-player level on Medium?', ' ', 20, 940);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Reserved for DLC: a new single-player level on Hard?', ' ', 20, 960);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Reserved for DLC: a new multiplayer map?', ' ', 20, 980);
INSERT INTO `achievement` (`av_s`, `av_f`, `score`, `total`) VALUES ('Reserved for DLC: a new multiplayer map?', ' ', 20, 1000);
